stages:
  - build
  - test
  - deploy

build:
  image: maven:3.8.6-jdk-17
  script:
    - mvn clean install
  only:
    - main

test:
  image: maven:3.8.6-jdk-17
  script:
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/*.xml
  only:
    - main

deploy:
  script:
    - echo "Deploying to production..."
  only:
    - main
