name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image and run tests
        run: |
          docker build -t ilp_submission_image:${{ github.sha }} .

      - name: Run Unit Tests in Docker container
        run: |
          docker run --rm ilp_submission_image:${{ github.sha }} mvn test -P unit

      - name: Run API Tests in Docker container
        run: |
          docker run --rm ilp_submission_image:${{ github.sha }} mvn test -P api

      - name: Push Docker image to Docker Hub (optional)
        if: success()
        run: |
          docker push panimcdermott/ilp_submission_image:${{ github.sha }}
