name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image and run tests
        run: |
          docker build -t ilp_submission_image:${{ github.sha }} .

      - name: Run Unit Tests in Docker container
        run: |
          docker run --rm ilp_submission_image:${{ github.sha }} mvn test -P unit

      - name: Run API Tests in Docker container
        run: |
          docker run --rm ilp_submission_image:${{ github.sha }} mvn test -P api

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ''
      - name: Build with Maven
        run: mvn clean test
