name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 3: Set up Java (JDK) with distribution
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify the Java version
          distribution: 'temurin'  # Specify the JDK distribution (temurin is a popular choice)
          java-package: jdk
          architecture: x64

      # Step 4: Run API Tests
      - name: Run API Tests
        run: mvn test -P api

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: mvn test -P unit

      # Step 6: Build Docker image and run tests
      - name: Build Docker image and run tests
        run: |
          docker build -t your-image-name:${{ github.sha }} .
          docker run --rm your-image-name:${{ github.sha }} mvn test