name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 3: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify the Java version
          distribution: 'temurin'  # Use Eclipse Temurin (Adoptium)

      # Step 4: Build the application
      - name: Build the application
        run: mvn clean install -DskipTests

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t your-image-name:${{ github.sha }} .

      # Step 6: Run the Spring Boot application in the background (detached mode)
      - name: Run Spring Boot application in detached mode
        run: |
          docker run -d --name app-container your-image-name:${{ github.sha }}

      # Step 7: Wait for the application to fully start (can use a sleep or health check)
      - name: Wait for the application to start
        run: sleep 10  # Adjust this based on your app startup time

      # Step 8: Run tests inside the container (while the app is running in the background)
      - name: Run tests in Docker container
        run: |
          docker exec app-container mvn test  # Run tests inside the container

      # Step 9: Shut down the Spring Boot application gracefully after tests
      - name: Gracefully shut down Spring Boot application
        run: |
          docker exec app-container curl -X POST http://localhost:8080/shutdown  # Use your shutdown endpoint

      # Step 10: Stop the container after tests and shutdown
      - name: Stop the Docker container
        run: docker stop app-container
