name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 3: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 4: Build the application
      - name: Build the application
        run: mvn clean install -DskipTests

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: docker build -t your-image-name:${{ github.sha }} .

      # Step 6: Run the Spring Boot application in detached mode
      - name: Run Spring Boot application
        run: docker run -d --name app-container -p 8080:8080 your-image-name:${{ github.sha }}

      # Step 7: Wait for the application to start
      - name: Wait for the application to start
        run: |
          for i in {1..12}; do
            if curl -s http://localhost:8080/actuator/health | grep 'UP'; then
              echo "Application is up!"
              break
            fi
            sleep 5
          done

      # Step 8: Print Docker logs (for debugging)
      - name: Print Docker logs
        run: docker logs app-container

      # Step 9: Run tests in Docker container
      - name: Run tests in Docker container
        run: docker exec app-container mvn test || docker logs app-container

      # Step 10: Gracefully shut down Spring Boot application
      - name: Gracefully shut down Spring Boot application
        run: curl -X POST http://localhost:8080/shutdown || echo "Shutdown failed, stopping container"

      # Step 11: Stop the Docker container
      - name: Stop the Docker container
        run: docker stop app-container
